[package]
name = "counter"
version = "0.0.1"

[addresses]
proof_forge = "_"

[dependencies]
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "main" }
