import Init.Notation
import Init.System.IO
import Lean
import Lean.Util.Path

open System

namespace ProofForge.Cli.Scaffold

def defaultGitUrl : String :=
  "https://github.com/DaviRain-Su/proof_forge.git"

def defaultTemplateId : String :=
  "portable-counter"

def initUsage : String :=
  String.intercalate "\n" [
    "Usage:",
    "  proof-forge init [DIR] [--template portable-counter]",
    "",
    "Scaffold a new chain-neutral contract_source project with a Counter stub,",
    "Lake package metadata, and a multi-target justfile."
  ]

structure ScaffoldOptions where
  dir : String
  templateId : String := defaultTemplateId
  deriving Inhabited

def sanitizePackageName (name : String) : String :=
  let trimmed := name.trimAscii.toString
  if trimmed.isEmpty then "counter" else trimmed

def replaceAll (s replacement needle : String) : String :=
  s.replace needle replacement

def renderTemplateFile (contents packageName gitUrl : String) : String :=
  replaceAll (replaceAll contents packageName "{{PACKAGE_NAME}}") gitUrl "{{PROOF_FORGE_GIT_URL}}"

def packageNameOfDir (dir : String) : String :=
  let path := FilePath.mk dir
  sanitizePackageName (path.fileName.getD "counter")

def renderReadme (packageName : String) : String :=
  s!"# {packageName}

Portable ProofForge starter generated by `proof-forge init`.

The contract imports `ProofForge.Contract.Source` and stays chain-neutral.
Select the backend with `proof-forge build --target <id>`.

## Setup

```sh
lake update
lake build Counter
lake build proofForge:proof-forge
```

## Build Artifacts

```sh
just build-evm
just build-solana
just build-near
just build-all
```

Or invoke the CLI directly:

```sh
lake env proof-forge build --target evm --root . \\
  -o build/evm/Counter.bin \\
  --yul-output build/evm/Counter.yul \\
  Counter.lean
```
"

def parseInitOptions (args : List String) : Except String ScaffoldOptions := do
  let mut dir? : Option String := none
  let mut templateId := defaultTemplateId
  let mut idx := 0
  while idx < args.length do
    let arg := args[idx]!
    if arg == "--template" then
      idx := idx + 1
      if idx >= args.length then
        throw "init --template requires a template id"
      templateId := args[idx]!
    else if arg.startsWith "--" then
      throw s!"unknown init option: {arg}\n{initUsage}"
    else if dir?.isSome then
      throw s!"unexpected argument: {arg}\n{initUsage}"
    else
      dir? := some arg
    idx := idx + 1
  let dir := dir?.getD "."
  if templateId != defaultTemplateId then
    throw s!"unknown template '{templateId}'\nknown templates: {defaultTemplateId}"
  return { dir, templateId }

def pathExists (path : String) : IO Bool :=
  (FilePath.mk path).pathExists

def readTextFile (path : String) : IO String :=
  IO.FS.readFile (FilePath.mk path)

def writeTextFile (path : String) (contents : String) : IO Unit := do
  let filePath := FilePath.mk path
  if let some parent := filePath.parent then
    IO.FS.createDirAll parent
  IO.FS.writeFile filePath contents

def directoryEmpty? (path : String) : IO Bool := do
  if !(← pathExists path) then
    return true
  let entries ← (FilePath.mk path).readDir
  return entries.isEmpty

def joinPath (dir fileName : String) : String :=
  (FilePath.mk dir / FilePath.mk fileName).toString

def findInSrcPath (parts : List String) : IO (Option String) := do
  match parts with
  | [] => return none
  | part :: rest => do
    if ← pathExists (joinPath part "templates/portable-counter/Counter.lean") then
      return some part
    else
      findInSrcPath rest

def findProofForgeRoot : IO (Option String) := do
  if let some srcPath ← IO.getEnv "LEAN_SRC_PATH" then
    if let some root ← findInSrcPath (String.splitOn srcPath ":") then
      return some root
  let mut dir := "."
  for _ in [0:32] do
    if ← pathExists (joinPath dir "templates/portable-counter/Counter.lean") then
      return some dir
    let parent := (FilePath.mk dir).parent
    match parent with
    | some value => dir := value.toString
    | none => return none
  return none

def normalizeGitRemote (remote : String) : String :=
  let trimmed := remote.trimAscii.toString
  let withoutAuth :=
    if trimmed.startsWith "git@" then
      let rest := (trimmed.drop 4).toString.replace ":" "/"
      s!"https://{rest}"
    else if trimmed.startsWith "https://" || trimmed.startsWith "http://" then
      trimmed
    else
      trimmed
  if withoutAuth.endsWith ".git" then withoutAuth else s!"{withoutAuth}.git"

def readGitRemoteUrl (root : String) : IO (Option String) := do
  try
    let r ← IO.Process.output {
      cmd := "git",
      args := #["-C", root, "config", "--get", "remote.origin.url"]
    }
    if r.exitCode == 0 then
      let url := normalizeGitRemote r.stdout
      if url.isEmpty then pure none else pure (some url)
    else
      pure none
  catch _ =>
    pure none

def resolveGitUrl (root : String) : IO String := do
  if let some url ← readGitRemoteUrl root then
    return url
  else
    return defaultGitUrl

def copyTemplateTextFile (templateDir targetDir fileName packageName gitUrl : String) : IO Unit := do
  let sourcePath := joinPath templateDir fileName
  if !(← pathExists sourcePath) then
    throw <| IO.userError s!"template is missing {sourcePath}"
  let contents ← readTextFile sourcePath
  writeTextFile (joinPath targetDir fileName) (renderTemplateFile contents packageName gitUrl)

def initCommand (opts : ScaffoldOptions) : IO UInt32 := do
  let root ← findProofForgeRoot
  let root ← match root with
    | some root => pure root
    | none =>
      throw <| IO.userError "proof-forge init could not locate templates/portable-counter; run from a ProofForge checkout or set LEAN_SRC_PATH"
  let targetDir := opts.dir
  if !(← directoryEmpty? targetDir) then
    throw <| IO.userError s!"init target directory is not empty: {targetDir}"
  let packageName := packageNameOfDir targetDir
  let gitUrl ← resolveGitUrl root
  let templateDir := joinPath (joinPath root "templates") opts.templateId
  let toolchainPath := joinPath root "lean-toolchain"
  if !(← pathExists (joinPath templateDir "Counter.lean")) then
    throw <| IO.userError s!"template '{opts.templateId}' is missing Counter.lean"
  if !(← pathExists toolchainPath) then
    throw <| IO.userError s!"missing lean-toolchain at {toolchainPath}"
  let counterSource ← readTextFile (joinPath templateDir "Counter.lean")
  let toolchain ← readTextFile toolchainPath
  writeTextFile (joinPath targetDir "Counter.lean") counterSource
  writeTextFile (joinPath targetDir "lean-toolchain") toolchain
  writeTextFile (joinPath targetDir "README.md") (renderReadme packageName)
  for fileName in ["lakefile.lean", "justfile", ".gitignore"] do
    copyTemplateTextFile templateDir targetDir fileName packageName gitUrl
  IO.println s!"init: wrote portable Counter starter to {targetDir}"
  IO.println "next steps:"
  IO.println s!"  cd {targetDir}"
  IO.println "  lake update"
  IO.println "  just build-evm"
  IO.println "  just build-solana"
  return 0

end ProofForge.Cli.Scaffold
