namespace ProofForge.Cli

def usage : String :=
  String.intercalate "\n" [
    "ProofForge — portable contract SDK",
    "",
    "Product path (preferred):",
    "  proof-forge init [DIR]                      # Product scaffold (business intent only)",
    "  proof-forge build --target <id> … input.lean  # materialize; id: evm | solana-sbpf-asm | wasm-near | …",
    "  proof-forge build --target <id> --token …    # TokenSpec → chain-native token plan/artifact",
    "  proof-forge check --target <id> …",
    "",
    "Authors write contract_source / TokenSpec only — no CPI/PDA/Promise/layout packing.",
    "See docs/product-sdk.md. Legacy emit/--learn flags remain below for fixtures/CI.",
    "",
    "Usage (legacy + full surface):",
    "  proof-forge [--root DIR] [--module Mod.Name] [-o output.yul] input.lean",
    "  proof-forge --evm-bytecode [--root DIR] [--module Mod.Name] [--yul-output file] [--artifact-output file] [--evm-chain-profile id] [--evm-constructor-param name:type] [--evm-constructor-arg name=value] [--evm-constructor-args-hex hex] [-o output.bin] input.lean",
    "  proof-forge --emit-counter-ir-yul [-o output.yul]",
    "  proof-forge --emit-counter-ir-ts [-o output.ts]",
    "  proof-forge --emit-counter-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-value-vault-ir-yul [-o output.yul]",
    "  proof-forge --emit-value-vault-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --learn --target evm [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin] input.learn",
    "  proof-forge --learn --target solana-sbpf-asm [-o output.s] [--artifact-output file] input.learn",
    "  proof-forge --learn-target <target-id> [target options] input.learn",
    "  proof-forge --learn-token --target evm [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin] input.learn|input.lean",
    "  proof-forge --learn-token --target solana-sbpf-asm [-o token-plan.json] input.learn|input.lean",
    "  proof-forge --learn-yul [-o output.yul] input.learn",
    "  proof-forge --learn-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin] input.learn",
    "  proof-forge --learn-sbpf [-o output.s] [--artifact-output file] input.learn",
    "  proof-forge --emit-abi-scalar-ir-yul [-o output.yul]",
    "  proof-forge --emit-abi-scalar-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-assert-ir-yul [-o output.yul]",
    "  proof-forge --emit-assert-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-assignment-ir-yul [-o output.yul]",
    "  proof-forge --emit-assignment-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-assign-op-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-assign-op-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-conditional-ir-yul [-o output.yul]",
    "  proof-forge --emit-conditional-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-context-ir-yul [-o output.yul]",
    "  proof-forge --emit-context-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-event-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-event-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-crosscall-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-crosscall-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-expression-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-expression-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-hash-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-hash-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-loop-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-loop-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-map-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-map-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-storage-array-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-storage-array-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-storage-struct-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-storage-struct-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-typed-map-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-typed-map-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-typed-storage-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-typed-storage-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-array-value-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-array-value-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-struct-array-value-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-struct-array-value-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-struct-value-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-struct-value-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-abi-aggregate-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-abi-aggregate-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-array-abi-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-array-abi-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-dynamic-abi-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-dynamic-abi-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-dynamic-array-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-dynamic-array-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-memory-array-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-memory-array-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-packed-storage-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-packed-storage-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-errors-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-errors-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-evm-fallback-ir-yul [-o output.yul]",
    "  proof-forge --emit-evm-fallback-ir-bytecode [--solc solc] [--yul-output output.yul] [--artifact-output file] [-o output.bin]",
    "  proof-forge --emit-counter-ir-psy [-o output.psy]",
    "  proof-forge --emit-event-ir-psy [-o output.psy]",
    "  proof-forge --emit-crosscall-ir-psy [-o output.psy]",
    "  proof-forge --emit-expression-predicate-ir-psy [-o output.psy]",
    "  proof-forge --emit-generic-entrypoint-ir-psy [-o output.psy]",
    "  proof-forge --emit-arithmetic-ir-psy [-o output.psy]",
    "  proof-forge --emit-bitwise-ir-psy [-o output.psy]",
    "  proof-forge --emit-bool-storage-array-ir-psy [-o output.psy]",
    "  proof-forge --emit-bool-storage-scalar-ir-psy [-o output.psy]",
    "  proof-forge --emit-conditional-ir-psy [-o output.psy]",
    "  proof-forge --emit-context-ir-psy [-o output.psy]",
    "  proof-forge --emit-hash-ir-psy [-o output.psy]",
    "  proof-forge --emit-hash-storage-ir-psy [-o output.psy]",
    "  proof-forge --emit-map-ir-psy [-o output.psy]",
    "  proof-forge --emit-assert-ir-psy [-o output.psy]",
    "  proof-forge --emit-loop-ir-psy [-o output.psy]",
    "  proof-forge --emit-array-ir-psy [-o output.psy]",
    "  proof-forge --emit-struct-ir-psy [-o output.psy]",
    "  proof-forge --emit-struct-array-ir-psy [-o output.psy]",
    "  proof-forge --emit-abi-aggregate-ir-psy [-o output.psy]",
    "  proof-forge --emit-nested-aggregate-ir-psy [-o output.psy]",
    "  proof-forge --emit-storage-nested-aggregate-ir-psy [-o output.psy]",
    "  proof-forge --emit-u32-arithmetic-ir-psy [-o output.psy]",
    "  proof-forge --emit-u32-hash-packing-ir-psy [-o output.psy]",
    "  proof-forge --emit-u32-storage-scalar-ir-psy [-o output.psy]",
    "  proof-forge --emit-u32-storage-array-ir-psy [-o output.psy]",
    "  proof-forge --emit-counter-ir-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-value-vault-ir-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-control-ir-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-solana-sdk-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-solana-system-cpi-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-solana-system-create-account-cpi-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-solana-spl-token-transfer-cpi-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-solana-spl-token-ops-cpi-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-solana-spl-token-close-account-cpi-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-solana-spl-token-authority-cpi-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-solana-associated-token-cpi-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-solana-spl-token-2022-cpi-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-solana-spl-token-2022-pausable-cpi-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-solana-spl-token-2022-transfer-hook-sbpf [-o output.s] [--artifact-output file]",
    "  proof-forge --solana-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --value-vault-solana-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-system-cpi-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-system-create-account-cpi-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-spl-token-transfer-cpi-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-spl-token-ops-cpi-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-spl-token-close-account-cpi-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-spl-token-authority-cpi-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-associated-token-cpi-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-spl-token-2022-cpi-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-spl-token-2022-pausable-cpi-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-spl-token-2022-transfer-hook-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-log-event-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-clock-sysvar-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-rent-sysvar-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-epoch-schedule-sysvar-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-epoch-rewards-sysvar-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-last-restart-slot-sysvar-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-memory-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-crypto-hash-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --solana-return-data-compute-elf [-o output.so] [--artifact-output file] [--solana-sbpf-arch v0|v3]",
    "  proof-forge --emit-sbpf-asm [-o output.s] [--artifact-output file]",
    "  proof-forge --emit-counter-ir-wasm-near -o output-dir",
    "  proof-forge --emit-counter-emitwat [-o output-dir] [--target wasm-near|wasm-cosmwasm]",
    "  proof-forge --emit-context-emitwat [-o output-dir] [--target wasm-near|wasm-cosmwasm]",
    "  proof-forge --emit-hash-emitwat [-o output-dir] [--target wasm-near|wasm-cosmwasm]",
    "  proof-forge --emit-map-emitwat [-o output-dir] [--target wasm-near|wasm-cosmwasm]",
    "  proof-forge --emit-context-ir-wasm-near -o output-dir",
    "  proof-forge --emit-hash-ir-wasm-near -o output-dir",
    "  proof-forge --emit-map-ir-wasm-near -o output-dir",
    "  proof-forge --emit-counter-ir-leo [-o output.leo]",
    "  proof-forge --emit-counter-ir-cosmwasm [-o output.wat]   (CosmWasm Counter spike)",
    "  proof-forge --emit-counter-ir-aptos [-o output-dir]       (Aptos Move Counter spike)",
    "  proof-forge --emit-counter-ir-sui [-o output-dir]         (Sui Move Counter MVP)",
    "  proof-forge --emit-counter-ir-quint [-o output.qnt]       (Quint Counter model)",
    "  proof-forge --emit-value-vault-ir-quint [-o output.qnt]    (Quint ValueVault model)",
    "  proof-forge --emit-ir-quint --fixture <id> [-o output.qnt] (Quint portable IR fixture model)",
    "  proof-forge --emit-ir-quint-scenario --fixture <id> [-o output.toml] (auto-generated Quint scenario TOML)",
    "  proof-forge init [DIR] [--template portable-counter]",
    "",
    "EVM bytecode mode loads `spec : ContractSpec` from the Lean module and uses Foundry `cast sig` plus `solc --strict-assembly`.",
    "`--evm-chain-profile <id>` records deployment profile metadata in the EVM deploy manifest without broadcasting transactions.",
    "`--evm-constructor-param name:type` records static-word constructor ABI schema metadata for an ABI-encoded constructor args blob.",
    "`--evm-constructor-arg name=value` ABI-encodes one typed constructor value using the declared constructor schema.",
    "`--evm-constructor-args-hex <hex>` appends ABI-encoded constructor arguments to generated EVM initcode.",
    "IR fixture modes render hand-written portable IR fixtures to target source or bytecode."
  ]

end ProofForge.Cli
