#![cfg(all(test, feature = "test-sbf"))]
//! ProofForge Control-Flow + Assertion V-GATE-SOLANA-08: Mollusk runtime smoke.
//!
//! Generated by `scripts/solana/control-smoke.sh` from this template.
//! The placeholder `__PROGRAM_NAME__` is replaced with the actual project
//! (and so file / keypair) name before the test is run.
//!
//! Instruction discriminant bytes:
//!   0 => lifecycle          (control.conditional + assert_eq success)
//!   1 => guarded_increment  (asssert fail path: exits 2 when count >= 5)
//!   2 => equality_guard     (assert_eq fail path: exits 3 when count != 7)

mod tests {
    use {
        mollusk_svm::{result::Check, Mollusk},
        solana_account::Account,
        solana_address::Address,
        solana_instruction::{AccountMeta, Instruction},
    };

    const COUNTER_DATA_LEN: usize = 8;

    fn program_id() -> Address {
        // Mirror the sbpf init template: the program id is the first 32 raw
        // bytes of the keypair JSON file. Mollusk loads the .so at this id.
        let keypair_bytes =
            std::fs::read("deploy/__PROGRAM_NAME__-keypair.json").unwrap();
        let mut arr = [0u8; 32];
        arr.copy_from_slice(&keypair_bytes[..32]);
        Address::new_from_array(arr)
    }

    fn mollusk() -> Mollusk {
        let pid = program_id();
        let mut mollusk = Mollusk::new(&pid, "deploy/__PROGRAM_NAME__");
        // Phase 1 lowering uses the legacy embedded account-data layout, not
        // the direct-mapping ABI. Disable the features that change the input
        // serialization and account pointer layout.
        mollusk.feature_set.account_data_direct_mapping = false;
        mollusk.feature_set.direct_account_pointers_in_program_input = false;
        mollusk.feature_set.virtual_address_space_adjustments = false;
        mollusk
    }

    fn ix(pid: Address, tag: u8, counter: Address) -> Instruction {
        Instruction::new_with_bytes(
            pid,
            &[tag],
            vec![AccountMeta::new(counter, false)],
        )
    }

    fn counter_account(seed: u64) -> Account {
        let mut account = Account::new(0, COUNTER_DATA_LEN, &program_id());
        account.data = seed.to_le_bytes().to_vec();
        account
    }

    #[test]
    fn test_lifecycle_from_zero() {
        let pid = program_id();
        let m = mollusk();
        let counter = Address::new_unique();

        let result = m.process_and_validate_instruction(
            &ix(pid, 0, counter),
            &[(counter, counter_account(0))],
            &[
                Check::success(),
                Check::account(&counter)
                    .data(&10u64.to_le_bytes())
                    .build(),
            ],
        );
        assert!(!result.program_result.is_err());
        // Then/else branches both converge on 10; the assert_eq passes.
        assert_eq!(result.return_data, 10u64.to_le_bytes().to_vec());
    }

    #[test]
    fn test_lifecycle_independent_of_input() {
        let pid = program_id();
        let m = mollusk();
        let counter = Address::new_unique();

        let result = m.process_and_validate_instruction(
            &ix(pid, 0, counter),
            &[(counter, counter_account(12345))],
            &[
                Check::success(),
                Check::account(&counter)
                    .data(&10u64.to_le_bytes())
                    .build(),
            ],
        );
        // The first statement overwrites count with 0, so no matter the
        // incoming data the conditional branches drive it back to 10.
        assert!(!result.program_result.is_err());
        assert_eq!(result.return_data, 10u64.to_le_bytes().to_vec());
    }

    #[test]
    fn test_guarded_increment_success() {
        let pid = program_id();
        let m = mollusk();
        let counter = Address::new_unique();

        let result = m.process_and_validate_instruction(
            &ix(pid, 1, counter),
            &[(counter, counter_account(3))],
            &[
                Check::success(),
                Check::account(&counter)
                    .data(&4u64.to_le_bytes())
                    .build(),
            ],
        );
        assert!(!result.program_result.is_err());
        assert_eq!(result.return_data, 4u64.to_le_bytes().to_vec());
    }

    #[test]
    fn test_guarded_increment_revert() {
        let pid = program_id();
        let m = mollusk();
        let counter = Address::new_unique();

        let result =
            m.process_and_validate_instruction(&ix(pid, 1, counter), &[(counter, counter_account(9))], &[]);
        // .assert counts >= 5 as failure → entrypoint returns 2 → Solana
        // surfaces it as InstructionError::Custom(2).
        assert!(
            result.program_result.is_err(),
            "guarded_increment with count >= 5 must revert via .assert"
        );
    }

    #[test]
    fn test_equality_guard_success() {
        let pid = program_id();
        let m = mollusk();
        let counter = Address::new_unique();

        let result = m.process_and_validate_instruction(
            &ix(pid, 2, counter),
            &[(counter, counter_account(7))],
            &[
                Check::success(),
                Check::account(&counter)
                    .data(&7u64.to_le_bytes())
                    .build(),
            ],
        );
        assert!(!result.program_result.is_err());
        assert_eq!(result.return_data, 7u64.to_le_bytes().to_vec());
    }

    #[test]
    fn test_equality_guard_revert() {
        let pid = program_id();
        let m = mollusk();
        let counter = Address::new_unique();

        let result = m
            .process_and_validate_instruction(&ix(pid, 2, counter), &[(counter, counter_account(42))], &[]);
        // .assertEq requires count == 7 otherwise the entrypoint returns 3.
        assert!(
            result.program_result.is_err(),
            "equality_guard with count != 7 must revert via .assertEq"
        );
    }
}