#![cfg(all(test, feature = "test-sbf"))]
//! ProofForge Counter V-GATE-SOLANA-03: Mollusk runtime smoke.
//!
//! Generated by `scripts/solana/counter-smoke.sh` from this template.
//! The placeholder `__PROGRAM_NAME__` is replaced with the actual project
//! (and so file / keypair) name before the test is run.

mod tests {
    use {
        mollusk_svm::{result::Check, Mollusk},
        solana_account::Account,
        solana_address::Address,
        solana_instruction::{AccountMeta, Instruction},
    };

    const COUNTER_DATA_LEN: usize = 8;

    fn program_id() -> Address {
        // Mirror the sbpf init template: the program id is the first 32 raw
        // bytes of the keypair JSON file. Mollusk loads the .so at this id.
        let keypair_bytes =
            std::fs::read("deploy/__PROGRAM_NAME__-keypair.json").unwrap();
        let mut arr = [0u8; 32];
        arr.copy_from_slice(&keypair_bytes[..32]);
        Address::new_from_array(arr)
    }

    fn mollusk() -> Mollusk {
        let pid = program_id();
        Mollusk::new(&pid, "deploy/__PROGRAM_NAME__")
    }

    /// Instruction discriminant bytes:
    ///   0 => initialize   (writes 0)
    ///   1 => increment    (reads + 1, writes)
    ///   2 => get          (writes value to return data)
    fn ix(pid: Address, tag: u8, counter: Address) -> Instruction {
        Instruction::new_with_bytes(
            pid,
            &[tag],
            vec![AccountMeta::new(counter, false)],
        )
    }

    #[test]
    fn test_initialize() {
        let pid = program_id();
        let m = mollusk();
        let counter = Address::new_unique();
        let counter_account = Account::new(0, COUNTER_DATA_LEN, &pid);

        let result = m.process_and_validate_instruction(
            &ix(pid, 0, counter),
            &[(counter, counter_account)],
            &[
                Check::success(),
                Check::account(&counter)
                    .data(&0u64.to_le_bytes())
                    .build(),
            ],
        );
        assert!(!result.program_result.is_err());
    }

    #[test]
    fn test_increment_from_zero() {
        let pid = program_id();
        let m = mollusk();
        let counter = Address::new_unique();
        let mut counter_account = Account::new(0, COUNTER_DATA_LEN, &pid);
        counter_account.data = 0u64.to_le_bytes().to_vec();

        let result = m.process_and_validate_instruction(
            &ix(pid, 1, counter),
            &[(counter, counter_account)],
            &[
                Check::success(),
                Check::account(&counter)
                    .data(&1u64.to_le_bytes())
                    .build(),
            ],
        );
        assert!(!result.program_result.is_err());
    }

    #[test]
    fn test_increment_from_five() {
        let pid = program_id();
        let m = mollusk();
        let counter = Address::new_unique();
        let mut counter_account = Account::new(0, COUNTER_DATA_LEN, &pid);
        counter_account.data = 5u64.to_le_bytes().to_vec();

        let result = m.process_and_validate_instruction(
            &ix(pid, 1, counter),
            &[(counter, counter_account)],
            &[
                Check::success(),
                Check::account(&counter)
                    .data(&6u64.to_le_bytes())
                    .build(),
            ],
        );
        assert!(!result.program_result.is_err());
    }

    #[test]
    fn test_get_return_data() {
        let pid = program_id();
        let m = mollusk();
        let counter = Address::new_unique();
        let mut counter_account = Account::new(0, COUNTER_DATA_LEN, &pid);
        counter_account.data = 42u64.to_le_bytes().to_vec();

        let result = m.process_and_validate_instruction(
            &ix(pid, 2, counter),
            &[(counter, counter_account)],
            &[Check::success()],
        );
        assert!(!result.program_result.is_err());
        // sol_set_return_data wrote the 8-byte count.
        assert_eq!(
            result.return_data,
            42u64.to_le_bytes().to_vec(),
            "get should return the count as 8 bytes little-endian"
        );
    }
}