#!/usr/bin/env bash
set -euo pipefail

# Compile the hand-written portable Counter IR to EVM runtime bytecode and run a
# narrow Foundry smoke test against the generated bytecode.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_DIR="${IR_EVM_OUT_DIR:-$ROOT/build/ir}"
FORGE_DIR="${IR_EVM_FORGE_DIR:-$ROOT/build/foundry-ir-counter-smoke}"
METADATA_FILE="${IR_EVM_METADATA:-$OUT_DIR/Counter.proof-forge-artifact.json}"

export PATH="$HOME/.foundry/bin:$PATH"

if ! command -v forge >/dev/null 2>&1; then
  echo "ir-counter-smoke: forge not found. Install Foundry, then re-run this script." >&2
  echo "ir-counter-smoke: https://getfoundry.sh/" >&2
  exit 127
fi

if ! command -v solc >/dev/null 2>&1; then
  echo "ir-counter-smoke: solc not found on PATH." >&2
  exit 127
fi

mkdir -p "$OUT_DIR"
"$ROOT/.lake/build/bin/proof-forge" --emit-counter-ir-bytecode \
  --yul-output "$OUT_DIR/Counter.yul" \
  --artifact-output "$METADATA_FILE" \
  -o "$OUT_DIR/Counter.bin"

python3 "$ROOT/scripts/evm/validate-artifact-metadata.py" \
  --root "$ROOT" \
  --expect-fixture Counter \
  --expect-source-kind portable-ir \
  --expect-capability storage.scalar \
  --expect-entrypoint initialize:8129fc1c \
  --expect-entrypoint increment:d09de08a \
  --expect-entrypoint get:6d4ce63c \
  "$METADATA_FILE"

counter_hex="$(tr -d '\n' < "$OUT_DIR/Counter.bin")"

rm -rf "$FORGE_DIR"
mkdir -p "$FORGE_DIR/test"

cat > "$FORGE_DIR/foundry.toml" <<'TOML'
[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true
TOML

cat > "$FORGE_DIR/test/ProofForgeIRCounterSmoke.t.sol" <<SOL
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface Vm {
    function etch(address target, bytes calldata newRuntimeBytecode) external;
}

contract ProofForgeIRCounterSmokeTest {
    Vm constant vm = Vm(address(uint160(uint256(keccak256("hevm cheat code")))));

    function assertTrue(bool value) internal pure {
        require(value, "assertTrue failed");
    }

    function assertFalse(bool value) internal pure {
        require(!value, "assertFalse failed");
    }

    function assertEq(uint256 actual, uint256 expected) internal pure {
        require(actual == expected, "assertEq failed");
    }

    function deployRuntime(bytes memory code, address target) internal {
        vm.etch(target, code);
    }

    function readCounter(address counter) internal returns (uint256) {
        (bool ok, bytes memory result) = counter.call(abi.encodeWithSignature("get()"));
        assertTrue(ok);
        return abi.decode(result, (uint256));
    }

    function testIRCounterLifecycle() public {
        address counter = address(0x1CED);
        deployRuntime(hex"$counter_hex", counter);

        assertEq(readCounter(counter), 0);

        (bool initOk,) = counter.call(abi.encodeWithSignature("initialize()"));
        assertTrue(initOk);
        assertEq(readCounter(counter), 0);

        (bool incOk1,) = counter.call(abi.encodeWithSignature("increment()"));
        assertTrue(incOk1);
        assertEq(readCounter(counter), 1);

        (bool incOk2,) = counter.call(abi.encodeWithSignature("increment()"));
        assertTrue(incOk2);
        assertEq(readCounter(counter), 2);

        (bool unknownOk,) = counter.call(hex"ffffffff");
        assertFalse(unknownOk);
    }
}
SOL

forge test --root "$FORGE_DIR" -vv

echo "ir-counter-smoke: ProofForge metadata $METADATA_FILE"
