#!/usr/bin/env python3
"""Generate docs/generated/backend-status.md from proof-forge --list-targets --json.

PF-P1-02: the JSON support matrix is authoritative; this table must stay in
zero-diff sync with the registry.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def load_matrix(root: Path) -> dict:
    proc = subprocess.run(
        ["lake", "env", "proof-forge", "--list-targets", "--json"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr or proc.stdout or "proof-forge --list-targets --json failed\n")
        sys.exit(proc.returncode or 1)
    return json.loads(proc.stdout)


def join_codes(values: list[str]) -> str:
    return ", ".join(f"`{v}`" for v in values)


def render(matrix: dict) -> str:
    lines = [
        "<!-- Generated by scripts/docs/generate-backend-status.py — do not edit by hand. -->",
        "# Backend status (machine-readable contract)",
        "",
        "Source: `proof-forge --list-targets --json` (PF-P1-02). Plain `--list-targets` remains",
        "registry membership only (PF-P0-02).",
        "",
        "| Target id | Maturity | Input modes | Commands | Output stages | Validation | Fragment |",
        "|---|---|---|---|---|---|---|",
    ]
    for target in matrix["targets"]:
        support = target["support"]
        fragment = support["supportedFragment"].replace("|", "\\|")
        lines.append(
            f"| `{target['id']}` | `{support['maturity']}` | {join_codes(support['inputModes'])} | "
            f"{join_codes(support['commands'])} | {join_codes(support['outputStages'])} | "
            f"`{support['validationLevel']}` | {fragment} |"
        )
    lines.append("")
    lines.append(f"_schemaVersion: {matrix.get('schemaVersion', '?')}_")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Regenerate and exit 1 if docs/generated/backend-status.md would change",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output path (default: docs/generated/backend-status.md)",
    )
    args = parser.parse_args()
    root = repo_root()
    out = args.out or (root / "docs/generated/backend-status.md")
    matrix = load_matrix(root)
    text = render(matrix)
    if args.check:
        if not out.is_file():
            print(f"missing generated table: {out}", file=sys.stderr)
            return 1
        existing = out.read_text()
        if existing != text:
            print(
                f"backend-status table out of date: {out}\n"
                "run: python3 scripts/docs/generate-backend-status.py",
                file=sys.stderr,
            )
            return 1
        print(f"backend-status: ok ({len(matrix['targets'])} targets)")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"wrote {out.relative_to(root)} ({len(matrix['targets'])} targets)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
