import ProofForge.Backend.WasmNear.Refinement
import ProofForge.Backend.Evm.Refinement
import ProofForge.Contract.Examples.ValueVaultInvariant
import ProofForge.IR.Semantics
import ProofForge.IR.Ownership
import ProofForge.IR.Examples.ArrayProbe

namespace ProofForge.Tests.NearWasmFormal

theorem release_then_sum_ownership_ok :
    ProofForge.IR.Ownership.checkEntrypointOk
      ProofForge.IR.Examples.ArrayProbe.releaseThenSum = true := by
  native_decide

#check ProofForge.IR.Semantics.counter_trace_gets_one
#check ProofForge.IR.Semantics.counter_exports_match_near_entrypoints
#check ProofForge.IR.Semantics.evalExpr_deterministic
#check ProofForge.IR.Semantics.execStatements_deterministic
#check ProofForge.IR.Semantics.runEntrypointWithArgs_deterministic
#check ProofForge.IR.Semantics.boundedForRemaining_decreases
#check ProofForge.IR.Semantics.array_sum_literal_trace_returns_sixty
#check ProofForge.IR.Semantics.array_storage_lifecycle_trace_returns_thirty_one
#check ProofForge.IR.Semantics.array_predicates_trace_returns_one
#check ProofForge.IR.Semantics.abi_sum_pair_trace_returns_forty_two
#check ProofForge.IR.Semantics.abi_make_array_trace_returns_array
#check ProofForge.IR.Semantics.map_lifecycle_trace_returns_fifty_five
#check ProofForge.IR.Semantics.map_contains_lifecycle_trace_returns_ninety_nine
#check ProofForge.IR.Semantics.map_parameterized_lifecycle_trace_matches
#check ProofForge.IR.Semantics.map_path_lifecycle_trace_returns_seventy_seven
#check ProofForge.IR.Semantics.map_path_assign_lifecycle_trace_returns_fifty_eight
#check ProofForge.IR.Semantics.map_nested_path_lifecycle_trace_returns_ninety_five
#check ProofForge.IR.Semantics.map_nested_path_dynamic_trace_returns_argument_value
#check ProofForge.IR.Semantics.storage_struct_path_lifecycle_trace_returns_forty_eight
#check ProofForge.IR.Semantics.storage_struct_lifecycle_trace_returns_eighteen
#check ProofForge.IR.Semantics.storage_struct_array_lifecycle_trace_returns_twelve
#check ProofForge.IR.Semantics.storage_struct_array_path_lifecycle_trace_returns_twenty_three
#check ProofForge.IR.Semantics.storage_struct_whole_write_trace_returns_seventy
#check ProofForge.IR.Semantics.storage_struct_whole_return_trace_returns_point
#check ProofForge.IR.Semantics.storage_struct_self_write_trace_returns_seven_hundred_five
#check ProofForge.IR.Semantics.storage_struct_return_points_trace_returns_array
#check ProofForge.IR.Semantics.abi_sum_array_trace_returns_fifteen
#check ProofForge.IR.Semantics.abi_sum_matrix_trace_returns_ten
#check ProofForge.IR.Semantics.abi_sum_pair_array_trace_returns_ten
#check ProofForge.IR.Semantics.abi_make_pair_trace_returns_struct
#check ProofForge.IR.Semantics.abi_make_pair_array_trace_returns_struct_array
#check ProofForge.IR.Semantics.abi_make_matrix_trace_returns_nested_array
#check ProofForge.IR.Semantics.abi_sum_small_trace_returns_nineteen
#check ProofForge.IR.Semantics.abi_sum_small_matrix_trace_returns_ten
#check ProofForge.IR.Semantics.abi_and_flags_trace_returns_false
#check ProofForge.IR.Semantics.abi_echo_hash_pair_trace_returns_right_hash
#check ProofForge.IR.Semantics.abi_make_hash_array_trace_returns_hash_array
#check ProofForge.Tests.NearWasmFormal.release_then_sum_ownership_ok
#check ProofForge.Backend.WasmNear.Refinement.counter_ir_observable_trace_ok
#check ProofForge.Backend.WasmNear.Refinement.counter_emitwat_exports_trace_entrypoints
#check ProofForge.Backend.WasmNear.Refinement.counter_emitwat_artifact_surface_ok
#check ProofForge.Backend.WasmNear.Refinement.counter_emitwat_host_import_signatures_ok
#check ProofForge.Backend.WasmNear.Refinement.counter_emitwat_offline_host_execution_surface_ok
#check ProofForge.Backend.WasmNear.Refinement.value_vault_emitwat_artifact_surface_ok
#check ProofForge.Backend.WasmNear.Refinement.value_vault_emitwat_host_import_signatures_ok
#check ProofForge.Backend.WasmNear.Refinement.value_vault_emitwat_offline_host_execution_surface_ok
#check ProofForge.Backend.WasmNear.Refinement.value_vault_offline_host_final_state_derives_from_invariant
#check ProofForge.Backend.WasmNear.Refinement.value_vault_offline_host_logs_derive_from_invariant_state
#check ProofForge.Backend.WasmNear.Refinement.value_vault_emitwat_backend_invariant_bridge_ok
#check ProofForge.Contract.Examples.ValueVaultInvariant.value_vault_default_trace_ok
#check ProofForge.Contract.Examples.ValueVaultInvariant.value_vault_accounting_invariant_trace_ok
#check ProofForge.Contract.Examples.ValueVaultInvariant.value_vault_net_value_invariant_trace_ok
#check ProofForge.Backend.Evm.Refinement.evm_map_ir_observable_trace_ok
#check ProofForge.Backend.Evm.Refinement.evm_map_contains_ir_observable_trace_ok
#check ProofForge.Backend.Evm.Refinement.conditional_ir_observable_trace_ok
#check ProofForge.Backend.Evm.Refinement.loop_ir_observable_trace_ok
#check ProofForge.Backend.Evm.Refinement.event_ir_observable_trace_ok
#check ProofForge.Backend.Evm.Refinement.typed_storage_ir_observable_trace_ok
#check ProofForge.Backend.Evm.Refinement.storage_struct_ir_observable_trace_ok
#check ProofForge.Backend.Evm.Refinement.abi_aggregate_ir_observable_trace_ok

end ProofForge.Tests.NearWasmFormal

def main : IO UInt32 := do
  IO.println "formal-anchors: ValueVault FV-8 IR invariants, NEAR artifact/offline-host/import-signature backend surfaces, and EVM FV-2/FV-4 IR trace anchors checked"
  return 0
