import ProofForge.Solana.Examples.Vault
import ProofForge.Solana.Examples.SystemCpi
import ProofForge.Solana.Examples.MemoCpi
import ProofForge.Solana.Examples.SystemCreateAccountCpi
import ProofForge.Solana.Examples.SplTokenTransferCheckedCpi
import ProofForge.Solana.Examples.SplTokenOpsCpi
import ProofForge.Solana.Examples.SplTokenCloseAccountCpi
import ProofForge.Solana.Examples.SplTokenAuthorityCpi
import ProofForge.Solana.Examples.AssociatedTokenCpi
import ProofForge.Solana.Examples.SplToken2022Cpi
import ProofForge.Solana.Examples.SplToken2022PausableCpi
import ProofForge.Solana.Examples.SplToken2022TransferHook
import ProofForge.Solana.Examples.AccountRealloc
import ProofForge.Solana.Examples.LogEvent
import ProofForge.Solana.Examples.Clock
import ProofForge.Solana.Examples.Rent
import ProofForge.Solana.Examples.EpochSchedule
import ProofForge.Solana.Examples.EpochRewards
import ProofForge.Solana.Examples.LastRestartSlot
import ProofForge.Solana.Examples.Memory
import ProofForge.Solana.Examples.Crypto
import ProofForge.Solana.Examples.ReturnDataCompute
