/-
Copyright (c) 2026 DaviRain. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

CosmWasm Counter spike (M1) — **Wasm-family host adapter**.

Package path: `ProofForge.Backend.WasmHost.CosmWasm` (not a top-level backend
next to Evm/Solana). Shared EmitWat core for NEAR/Soroban is
`WasmHost.EmitWat` + `HostBridge`; CosmWasm currently uses a Counter-specific
static WAT emitter that passes `cosmwasm-check` (`instantiate` / `execute` /
`query`). Full IR→EmitWat unification with `HostBridge.cosmWasm` is follow-on.
-/
import Init.Data.Array.Basic
import Init.Data.String.Basic
import ProofForge.IR.Contract
import ProofForge.IR.Ownership
import ProofForge.Target.Check
import ProofForge.Target.Registry
import ProofForge.Backend.WasmHost.CosmWasm.IR

namespace ProofForge.Backend.WasmHost.CosmWasm.EmitWat

open ProofForge.IR
open ProofForge.Target

structure EmitError where
  message : String
  deriving Repr, Inhabited

def err (msg : String) : Except EmitError α := .error { message := msg }

/-- Capabilities supported by the CosmWasm Counter spike. -/
def supportedCapabilities : CapabilitySet := #[
  .storageScalar,
  .callerSender,
  .envBlock,
  .cryptoHash,
  .accountExplicit,
  .controlConditional,
  .controlBoundedLoop,
  .assertions
]

def checkCapabilities (mod : ProofForge.IR.Module) : Except EmitError Unit :=
  mod.capabilities.foldlM (fun _ c =>
    if supportedCapabilities.contains c then .ok ()
    else .error { message := s!"CosmWasm Counter spike: capability `{c.id}` is not supported" }) ()

/-- The static WAT module for the Counter fixture. It is parameterized only by
the module name and validates through `wat2wasm` + `cosmwasm-check`. -/
def counterWat (_moduleName : String) : String :=
  String.intercalate "\n" (#[
    "(module",
    "  ;; CosmWasm Counter spike generated by ProofForge",
    "  (import \"env\" \"db_read\" (func $db_read (param i32) (result i32)))",
    "  (import \"env\" \"db_write\" (func $db_write (param i32 i32)))",
    "",
    "  (memory (export \"memory\") 4)",
    "",
    "  ;; Static data segments",
    "  ;; Storage key \"count\" placed at a non-zero address to satisfy cosmwasm-vm region validation.",
    "  (data (i32.const 16) \"count\")",
    "  ;; ContractResult<Response> JSON template for instantiate/execute",
    "  (data (i32.const 32) \"{\\\"ok\\\":{\\\"messages\\\":[],\\\"attributes\\\":[],\\\"events\\\":[],\\\"data\\\":null}}\")",
    "  ;; ContractResult<Binary> JSON template for query (base64 of {\\\"count\\\":\\\"1\\\"})",
    "  (data (i32.const 96) \"{\\\"ok\\\":\\\"eyJjb3VudCI6IjEifQ==\\\"}\")",
    "  ;; Region for storage key \"count\": { offset=16, capacity=5, length=5 }",
    "  (data (i32.const 136) \"\\10\\00\\00\\00\\05\\00\\00\\00\\05\\00\\00\\00\")",
    "  ;; Region for storage value write: { offset=160, capacity=8, length=8 }",
    "  (data (i32.const 148) \"\\a0\\00\\00\\00\\08\\00\\00\\00\\08\\00\\00\\00\")",
    "",
    "  ;; Region allocator bump pointer",
    "  (global $alloc_ptr (mut i32) (i32.const 256))",
    "",
    "  ;; Interface version marker export (required by cosmwasm-check)",
    "  (func $interface_version_8)",
    "  (export \"interface_version_8\" (func $interface_version_8))",
    "",
    "  ;; allocate(size: u32) -> i32",
    "  ;; Returns a Region { offset, capacity, length }",
    "  (func $allocate (param $size i32) (result i32)",
    "    (local $ptr i32)",
    "    (local $data_ptr i32)",
    "    (local.set $ptr (global.get $alloc_ptr))",
    "    (local.set $data_ptr (i32.add (local.get $ptr) (i32.const 12)))",
    "    (i32.store (local.get $ptr) (local.get $data_ptr))",
    "    (i32.store offset=4 (local.get $ptr) (local.get $size))",
    "    (i32.store offset=8 (local.get $ptr) (i32.const 0))",
    "    (global.set $alloc_ptr",
    "      (i32.and",
    "        (i32.add (i32.add (local.get $data_ptr) (local.get $size)) (i32.const 7))",
    "        (i32.const 0xfffffff8)))",
    "    (local.get $ptr))",
    "",
    "  ;; deallocate(pointer: i32)",
    "  (func $deallocate (param $ptr i32))",
    "",
    "  ;; memcpy: manual byte copy loop (no bulk memory)",
    "  (func $memcpy (param $dst i32) (param $src i32) (param $n i32)",
    "    (local $i i32)",
    "    (block $done",
    "      (loop $loop",
    "        (br_if $done (i32.ge_u (local.get $i) (local.get $n)))",
    "        (i32.store8",
    "          (i32.add (local.get $dst) (local.get $i))",
    "          (i32.load8_u (i32.add (local.get $src) (local.get $i))))",
    "        (local.set $i (i32.add (local.get $i) (i32.const 1)))",
    "        (br $loop))))",
    "",
    "  ;; write_response(region_ptr, src_addr, len) -> region_ptr",
    "  ;; Copies src..src+len into the region's data buffer and sets region.length.",
    "  (func $write_response (param $region i32) (param $src i32) (param $len i32) (result i32)",
    "    (call $memcpy (i32.load (local.get $region)) (local.get $src) (local.get $len))",
    "    (i32.store offset=8 (local.get $region) (local.get $len))",
    "    (local.get $region))",
    "",
    "  ;; read_count: read u64 from storage key \"count\"",
    "  (func $read_count (result i64)",
    "    (local $value_region i32)",
    "    (local.set $value_region (call $db_read (i32.const 136)))",
    "    (if (i32.eqz (local.get $value_region))",
    "      (then (return (i64.const 0))))",
    "    (i64.load (i32.load (local.get $value_region))))",
    "",
    "  ;; write_count: write u64 value to storage key \"count\"",
    "  (func $write_count (param $v i64)",
    "    (i64.store (i32.const 160) (local.get $v))",
    "    (call $db_write (i32.const 136) (i32.const 148)))",
    "",
    "  ;; instantiate(env_ptr: i32, info_ptr: i32, msg_ptr: i32) -> result_ptr",
    "  (func $instantiate (param $env_ptr i32) (param $info_ptr i32) (param $msg_ptr i32) (result i32)",
    "    (call $write_count (i64.const 0))",
    "    (call $write_response (call $allocate (i32.const 62)) (i32.const 32) (i32.const 62)))",
    "",
    "  ;; execute(env_ptr: i32, info_ptr: i32, msg_ptr: i32) -> result_ptr",
    "  (func $execute (param $env_ptr i32) (param $info_ptr i32) (param $msg_ptr i32) (result i32)",
    "    (local $n i64)",
    "    (local.set $n (call $read_count))",
    "    (call $write_count (i64.add (local.get $n) (i64.const 1)))",
    "    (call $write_response (call $allocate (i32.const 62)) (i32.const 32) (i32.const 62)))",
    "",
    "  ;; query(env_ptr: i32, msg_ptr: i32) -> result_ptr",
    "  (func $query (param $env_ptr i32) (param $msg_ptr i32) (result i32)",
    "    (call $write_response (call $allocate (i32.const 29)) (i32.const 96) (i32.const 29)))",
    "",
    "  (export \"allocate\" (func $allocate))",
    "  (export \"deallocate\" (func $deallocate))",
    "  (export \"instantiate\" (func $instantiate))",
    "  (export \"execute\" (func $execute))",
    "  (export \"query\" (func $query))",
    ")",
  ].toList)

def renderModule (mod : ProofForge.IR.Module) : Except EmitError String := do
  checkCapabilities mod
  match ProofForge.IR.Ownership.checkModule mod with
  | .ok _ => pure ()
  | .error error => err s!"CosmWasm EmitWat: {error.render}"
  -- M1: only the Counter shape is supported; reject anything else by capability check.
  if mod.state.any (fun s => s.kind != .scalar || (s.type != .u32 && s.type != .u64 && s.type != .bool)) then
    err "CosmWasm Counter spike: only scalar u32/u64/bool storage is supported"
  if mod.entrypoints.any (fun ep => ep.params.size != 0) then
    err "CosmWasm Counter spike: entrypoints with parameters are not supported"
  pure (counterWat mod.name)

end ProofForge.Backend.WasmHost.CosmWasm.EmitWat
