import ProofForge.Backend.WasmNear.WasmInterpreter

/-! ## CosmWasm host bridge model for the in-Lean Wasm interpreter.

This is the WASM-5 chain axis: it instantiates the generic `WasmExec` core with
CosmWasm-style storage/read/write/return host functions. The storage model is
intentionally identical to NEAR's (`lookupStorage?` / `writeStorage`) so that
contract-axis proofs can reuse the same abstract storage reasoning; only the
host-call names and stack arities differ.

Keep this file thin: generic stack-machine lemmas live in `WasmExec.lean`, and
contract-specific refinements live in `ValueVaultWasmExec.lean` /
`CounterWasmRefinement.lean`.
-/

namespace ProofForge.Backend.WasmNear.CosmWasmHost

open ProofForge.Backend.WasmNear.WasmInterpreter

/-- CosmWasm host function arities as exposed to the Wasm module.

These match the standard `env` imports generated by `EmitWat` for CosmWasm
 targets. -/
def cosmWasmHostArity (name : String) : Except String Nat :=
  match name with
  | "db_read" => .ok 2
  | "db_write" => .ok 2
  | "db_remove" => .ok 2
  | "set_return_data" => .ok 2
  | "log" => .ok 2
  | other => .error s!"unsupported CosmWasm host call `{other}`"

/-- Read a U64 scalar from host storage at the key pointed to by the first stack
argument (key pointer) with length given by the second argument.

For the abstract model we ignore the pointer arithmetic and treat the key as the
provided byte vector; real CosmWasm contracts pass offsets into linear memory. -/
def runCosmWasmStorageRead (args : Array Nat) (state : WasmState) : Except String WasmState :=
  if h : args.size = 2 then
    let keyPtr := args[0]
    let keyLen := args[1]
    let key : Bytes := readBytes state.memory keyPtr keyLen
    match lookupStorage? state.host.storage key with
    | some value =>
        -- Push the loaded bytes onto the stack as a little-endian U64.
        let valueNat := leBytesToNat value
        .ok { state with valueStack := state.valueStack.push valueNat }
    | none =>
        -- Missing storage reads as 0, matching the NEAR model.
        .ok { state with valueStack := state.valueStack.push 0 }
  else
    .error s!"db_read expected 2 arguments, got {args.size}"

/-- Write the bytes popped from the stack as the value for the key popped first.

Stack discipline: [keyPtr, keyLen, valuePtr, valueLen] (db_write in CosmWasm
consumes 4 arguments; for our abstract scalar model we collapse value to a
pointer/length pair and encode the scalar as LE bytes). -/
def runCosmWasmStorageWrite (args : Array Nat) (state : WasmState) : Except String WasmState :=
  if h : args.size = 4 then
    let keyPtr := args[0]
    let keyLen := args[1]
    let valuePtr := args[2]
    let valueLen := args[3]
    let key : Bytes := readBytes state.memory keyPtr keyLen
    let valueBytes : Bytes := readBytes state.memory valuePtr valueLen
    .ok { state with host := { state.host with storage := writeStorage state.host.storage key valueBytes } }
  else
    .error s!"db_write expected 4 arguments, got {args.size}"

/-- Set the host return value from the pointer/length pair on the stack. -/
def runCosmWasmSetReturnData (args : Array Nat) (state : WasmState) : Except String WasmState :=
  if h : args.size = 2 then
    let ptr := args[0]
    let len := args[1]
    let value : Bytes := readBytes state.memory ptr len
    .ok { state with host := { state.host with returnValue := value } }
  else
    .error s!"set_return_data expected 2 arguments, got {args.size}"

/-- Dispatch a CosmWasm host call by name. -/
def runCosmWasmHostCall (name : String) (args : Array Nat) (state : WasmState) : Except String WasmState :=
  match name with
  | "db_read" => runCosmWasmStorageRead args state
  | "db_write" => runCosmWasmStorageWrite args state
  | "db_remove" => .ok state  -- abstract model: removal is a no-op
  | "set_return_data" => runCosmWasmSetReturnData args state
  | "log" => .ok state         -- events are not modeled at this layer
  | other => .error s!"unsupported CosmWasm host call `{other}`"

/-- Register the CosmWasm host bridge in `WasmInterpreter.runHostCall`.

This is the dispatch extension point: the interpreter sees `bridge = .cosmWasm`
and routes host calls here. -/
def runCosmWasmHostCallStep (name : String) : WasmState → Except String WasmState :=
  runHostCallWith cosmWasmHostArity runCosmWasmHostCall name

/-- Lemma: `db_write` with a single scalar value byte vector stores exactly that
byte vector at the given key. -/
theorem runCosmWasmStorageWrite_eq
    {state : WasmState} {key value : Bytes}
    (hkey : readBytes state.memory keyPtr keyLen = key)
    (hvalue : readBytes state.memory valuePtr valueLen = value) :
    runCosmWasmStorageWrite #[keyPtr, keyLen, valuePtr, valueLen] state =
      .ok { state with host := { state.host with storage := writeStorage state.host.storage key value } } := by
  simp [runCosmWasmStorageWrite, hkey, hvalue]

/-- Lemma: `db_read` returns the little-endian decoding of the stored bytes,
falling back to 0 when the key is absent. -/
theorem runCosmWasmStorageRead_eq
    {state : WasmState} {key : Bytes}
    (hkey : readBytes state.memory keyPtr keyLen = key) :
    let loaded : Nat :=
      match lookupStorage? state.host.storage key with
      | some value => leBytesToNat value
      | none => 0
    runCosmWasmStorageRead #[keyPtr, keyLen] state =
      .ok { state with valueStack := state.valueStack.push loaded } := by
  simp [runCosmWasmStorageRead, hkey]
  split <;> simp

/-- Lemma: `set_return_data` copies the requested memory slice into
`host.returnValue`. -/
theorem runCosmWasmSetReturnData_eq
    {state : WasmState} {value : Bytes}
    (hvalue : readBytes state.memory ptr len = value) :
    runCosmWasmSetReturnData #[ptr, len] state =
      .ok { state with host := { state.host with returnValue := value } } := by
  simp [runCosmWasmSetReturnData, hvalue]

end ProofForge.Backend.WasmNear.CosmWasmHost
