#!/usr/bin/env bash
# PF-P0-01: every registered target either lowers ValueVault (source identity) or
# rejects the source with a stable diagnostic — never silent Counter substitution.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

# Foundry tools may live outside the non-interactive PATH.
export PATH="${HOME}/.foundry/bin:${HOME}/.local/bin:${PATH}"

OUT_ROOT="${PROOF_FORGE_SOURCE_IDENTITY_OUT:-build/source-identity}"
SOURCE="${PROOF_FORGE_SOURCE_IDENTITY_SOURCE:-Examples/Product/ValueVault.lean}"

rm -rf "$OUT_ROOT"
mkdir -p "$OUT_ROOT"

lake build proof-forge >/dev/null

# Bash 3.2 compatible (macOS /bin/bash): avoid mapfile.
TARGETS=()
while IFS= read -r target; do
  [[ -n "$target" ]] && TARGETS+=("$target")
done < <(lake env proof-forge --list-targets)
if [[ "${#TARGETS[@]}" -eq 0 ]]; then
  echo "source-identity: --list-targets returned no ids" >&2
  exit 1
fi

fail() {
  echo "source-identity: $*" >&2
  exit 1
}

# Fixture-only Spike/MVP/Research targets: source build must fail closed.
is_fixture_only() {
  case "$1" in
    wasm-cosmwasm|psy-dpn|aleo-leo|move-aptos|move-sui|wasm-cloudflare-workers) return 0 ;;
    *) return 1 ;;
  esac
}

# Primary / host-bridge product targets expected to accept contract_source.
is_source_supported() {
  case "$1" in
    evm|solana-sbpf-asm|wasm-near|wasm-stellar-soroban) return 0 ;;
    *) return 1 ;;
  esac
}

looks_like_counter_product() {
  local path="$1"
  [[ -e "$path" ]] || return 1
  rg -n \
    'module proof_forge::counter|CosmWasm Counter|portable Counter IR|program counter\.aleo|struct Counter has key|// Generated by ProofForge from the portable Counter' \
    "$path" >/dev/null 2>&1
}

contains_valuevault() {
  local path="$1"
  [[ -e "$path" ]] || return 1
  rg -n --ignore-case 'ValueVault' "$path" >/dev/null 2>&1
}

build_one() {
  local target="$1"
  local out_dir="$OUT_ROOT/$target"
  local stdout_log="$out_dir/stdout.log"
  local stderr_log="$out_dir/stderr.log"
  local status=0
  local out_arg=""
  local extra=()

  mkdir -p "$out_dir"
  : >"$stdout_log"
  : >"$stderr_log"

  case "$target" in
    evm)
      # Prefer Yul when cast/solc bytecode path is unavailable; identity still holds.
      if command -v solc >/dev/null 2>&1 && command -v cast >/dev/null 2>&1; then
        out_arg="$out_dir/ValueVault.bin"
        extra+=(--yul-output "$out_dir/ValueVault.yul" --artifact-output "$out_dir/ValueVault.proof-forge-artifact.json")
      else
        out_arg="$out_dir/ValueVault.yul"
        extra+=(--format yul --artifact-output "$out_dir/ValueVault.proof-forge-artifact.json")
      fi
      ;;
    solana-sbpf-asm)
      # Default final artifact is ELF (PF-P0-03).
      out_arg="$out_dir/ValueVault.so"
      extra+=(--artifact-output "$out_dir/ValueVault.proof-forge-artifact.json")
      ;;
    wasm-near|wasm-stellar-soroban)
      out_arg="$out_dir"
      extra+=(--artifact-output "$out_dir/ValueVault.proof-forge-artifact.json")
      ;;
    *)
      out_arg="$out_dir/out"
      ;;
  esac

  set +e
  # Bash 3.2 + set -u: empty arrays cannot be expanded with "${arr[@]}".
  if [[ ${#extra[@]} -gt 0 ]]; then
    lake env proof-forge build --target "$target" --root . -o "$out_arg" "${extra[@]}" "$SOURCE" \
      >"$stdout_log" 2>"$stderr_log"
  else
    lake env proof-forge build --target "$target" --root . -o "$out_arg" "$SOURCE" \
      >"$stdout_log" 2>"$stderr_log"
  fi
  status=$?
  set -e

  if [[ "$status" -eq 0 ]]; then
    if looks_like_counter_product "$out_dir"; then
      fail "target $target succeeded but artifact looks like Counter under $out_dir"
    fi
    if ! contains_valuevault "$out_dir"; then
      fail "target $target succeeded but produced no ValueVault identity under $out_dir"
    fi
    echo "source-identity: $target ok (ValueVault source)"
    return 0
  fi

  # Failure path: never leave Counter product artifacts.
  if looks_like_counter_product "$out_dir"; then
    fail "target $target failed but still wrote Counter-looking content under $out_dir"
  fi

  if is_fixture_only "$target"; then
    if ! grep -Fq "source input is not supported" "$stderr_log"; then
      echo "source-identity: $target missing 'source input is not supported'" >&2
      echo "stderr:" >&2
      cat "$stderr_log" >&2
      exit 1
    fi
    echo "source-identity: $target ok (rejected source)"
    return 0
  fi

  if is_source_supported "$target"; then
    echo "source-identity: $target expected source success but failed" >&2
    echo "stderr:" >&2
    cat "$stderr_log" >&2
    exit 1
  fi

  # Other registered targets: honest nonzero exit without Counter is acceptable.
  echo "source-identity: $target ok (fail-closed; non-fixture diagnostic)"
}

for target in "${TARGETS[@]}"; do
  build_one "$target"
done

echo "source-identity: ok (${#TARGETS[@]} targets)"
