# ProofForge generated Solana instruction manifest
target = "solana-sbpf-asm"

[program]
id = "REPLACE_WITH_PROGRAM_ID"
name = "valuevault"

[[instruction]]
name = "initialize"
tag = 0
handler = "sol_initialize"
min_data_len = 9
accounts = [
  { name = "balance", index = 0, signer = false, writable = true, owner = "program" }
]
params = [
  { name = "initial", type = "U64", offset = 1, byte_size = 8, encoding = "le-u64" }
]

[[instruction]]
name = "deposit"
tag = 1
handler = "sol_deposit"
min_data_len = 9
accounts = [
  { name = "balance", index = 0, signer = false, writable = true, owner = "program" }
]
params = [
  { name = "amount", type = "U64", offset = 1, byte_size = 8, encoding = "le-u64" }
]

[[instruction]]
name = "charge_fee"
tag = 2
handler = "sol_charge_fee"
min_data_len = 17
accounts = [
  { name = "balance", index = 0, signer = false, writable = true, owner = "program" }
]
params = [
  { name = "gross", type = "U64", offset = 1, byte_size = 8, encoding = "le-u64" },
  { name = "fee_bps", type = "U64", offset = 9, byte_size = 8, encoding = "le-u64" }
]

[[instruction]]
name = "release"
tag = 3
handler = "sol_release"
min_data_len = 9
accounts = [
  { name = "balance", index = 0, signer = false, writable = true, owner = "program" }
]
params = [
  { name = "amount", type = "U64", offset = 1, byte_size = 8, encoding = "le-u64" }
]

[[instruction]]
name = "snapshot"
tag = 4
handler = "sol_snapshot"
min_data_len = 1
accounts = [
  { name = "balance", index = 0, signer = false, writable = true, owner = "program" }
]
params = []

[[instruction]]
name = "get_balance"
tag = 5
handler = "sol_get_balance"
min_data_len = 1
accounts = [
  { name = "balance", index = 0, signer = false, writable = true, owner = "program" }
]
params = []

[[instruction]]
name = "get_net_value"
tag = 6
handler = "sol_get_net_value"
min_data_len = 1
accounts = [
  { name = "balance", index = 0, signer = false, writable = true, owner = "program" }
]
params = []
