#!/usr/bin/env python3
"""Regenerate testkit/compare/MATRIX.md from live sandbox-report.json files.

Usage (repo root):
  python3 scripts/near/compare-matrix-snapshot.py
"""

from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REPORT_ROOT = ROOT / "build/testkit/compare/near"
OUT = ROOT / "testkit/compare/MATRIX.md"

KINDS = {
    "counter": "baseline",
    "value-vault": "state",
    "fungible-token": "NEP-141 body",
    "ownable": "access",
    "staking-vault": "deposit map",
    "role-gated-token": "nested roles",
    "fee-token": "FT+fee",
    "remote-call": "promise",
    "status-message": "map U64",
    "guestbook": "maps U64",
    "storage-deposit": "NEP-145-lite",
    "pausable": "mixin",
    "reentrancy-guard": "mixin",
    "ownable-pausable": "compose",
    "array-example": "pure",
    "ownable-hash": "hash owner",
    "host-env-probe": "host env",
    "auth-remote-call": "promise+debit",
    "access-control": "roles",
    "external-token-transfer": "NEP-141 client",
    "external-vault": "vault client",
    "pro-rata-vault": "share vault",
    "soulbound-token": "non-transferable",
    "ft-peer-client": "protocol FT client",
    "vesting-vault": "HostEnv vesting",
    "escrow-vault": "escrow state machine",
    "timelock-vault": "HostEnv timelock",
    "height-lock-vault": "HostEnv height lock",
}


def main() -> int:
    if not REPORT_ROOT.is_dir():
        print(f"missing reports dir: {REPORT_ROOT}", file=sys.stderr)
        return 1
    rows = []
    for d in sorted(REPORT_ROOT.iterdir()):
        p = d / "sandbox-report.json"
        if not p.is_file():
            continue
        r = json.loads(p.read_text())
        c = r.get("comparison") or {}
        w = c.get("wasmBytes") or {}
        cg = c.get("callGasBurnt") or {}
        st = c.get("storageUsageBytes") or {}
        wx = w.get("nearSdk_vs_proofForge_ratio")
        cx = cg.get("nearSdk_vs_proofForge_ratio")
        sx = st.get("nearSdk_vs_proofForge_ratio")
        rows.append(
            {
                "id": d.name,
                "contract": r.get("contract") or d.name,
                "pf": int(w.get("proofForge") or 0),
                "sdk": int(w.get("nearSdk") or 0),
                "wx": float(wx) if wx is not None else 0.0,
                "cx": float(cx) if cx is not None else None,
                "sx": float(sx) if sx is not None else None,
            }
        )
    if not rows:
        print("no sandbox-report.json found", file=sys.stderr)
        return 1
    rows.sort(key=lambda x: x["wx"], reverse=True)
    wxs = [r["wx"] for r in rows]
    cxs = [r["cx"] for r in rows if r["cx"] is not None]

    lines: list[str] = []
    lines.append("# NEAR compare matrix — full snapshot\n\n")
    lines.append("**Generated by** `scripts/near/compare-matrix-snapshot.py`  \n")
    lines.append(f"**Live dual-deploy contracts:** **{len(rows)}**  \n")
    lines.append("**Ratio:** near-sdk ÷ ProofForge\n\n")
    lines.append("## Leaderboard (wasm×)\n\n")
    lines.append(
        "| Rank | Contract | PF wasm | sdk wasm | **wasm×** | call× | storage× | Kind |\n"
    )
    lines.append(
        "|-----:|----------|--------:|---------:|----------:|------:|---------:|------|\n"
    )
    for i, r in enumerate(rows, 1):
        cx = f"{r['cx']:.2f}" if r["cx"] is not None else "—"
        sx = f"{r['sx']:.1f}" if r["sx"] is not None else "—"
        lines.append(
            f"| {i} | {r['contract']} | {r['pf']} | {r['sdk']} | "
            f"**~{r['wx']:.1f}×** | {cx}× | {sx}× | {KINDS.get(r['id'], '')} |\n"
        )
    lines.append("\n### Stats\n\n")
    lines.append("| Stat | wasm× | call× |\n|------|------:|------:|\n")
    lines.append(f"| min | {min(wxs):.1f}× | {min(cxs):.2f}× |\n")
    lines.append(
        f"| **median** | **{statistics.median(wxs):.1f}×** | **{statistics.median(cxs):.2f}×** |\n"
    )
    lines.append(f"| mean | {statistics.mean(wxs):.1f}× | {statistics.mean(cxs):.2f}× |\n")
    lines.append(f"| max | {max(wxs):.1f}× | {max(cxs):.2f}× |\n")
    lines.append("\n### Takeaways\n\n")
    lines.append(
        "1. PF wasm advantage remains large vs near-sdk (framework-free EmitWat).\n"
    )
    lines.append(
        "2. Call gas stays near parity (~1.05–1.26×); storage host ops dominate.\n"
    )
    lines.append(
        "3. Blocked Product: full Stdlib.ERC4626 (NEAR asset crosscall strings); "
        "TokenSpec-only Soulbound plan (body is SoulboundTokenBody).\n"
    )
    lines.append("\n```sh\njust near-compare-matrix\njust near-compare-all-live\n```\n")
    OUT.write_text("".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} contracts)")
    print(
        f"median wasm×={statistics.median(wxs):.1f} call×={statistics.median(cxs):.2f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
