name: Secret Scan

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  trufflehog:
    name: TruffleHog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          fetch-depth: 0

      - name: Secret scan
        uses: trufflesecurity/trufflehog@09c910786129b9e77f49a1ffadace09317291741  # main
        with:
          extra_args: --only-verified
